"""
Reads audit_log.jsonl back and computes M1, M2, M6 with real numbers.
M7 (provider-invariance) and M8 (failover survival) need the same
scenario set forced through each provider explicitly — that's Step 11's
job, not this file's; what's here reports what actually happened in
whichever providers the router picked naturally.

Run: .venv\\Scripts\\python.exe audit\\report.py
"""

import os
import sys
from datetime import datetime, timezone

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from dotenv import load_dotenv

load_dotenv()

from audit.logger import read_all
from domain.cart import init_cart_tables
from domain.catalog import init_db
from domain.orders import init_order_tables
from tests.scenarios import SCENARIOS, run_scenarios


def compute_metrics() -> dict:
    # The log is append-only by design (never cleared, never rewritten)
    # — rerunning this script without deleting it would otherwise
    # double-count a previous run's events under the same session ids.
    # Scoping to events at-or-after this run's start keeps the file's
    # full history intact while still reporting only THIS run's numbers.
    run_start = datetime.now(timezone.utc).isoformat()
    scenario_results = run_scenarios(verbose=False)
    events = [e for e in read_all() if e.get("ts", "") >= run_start]

    total = len(scenario_results)
    passed = sum(r["passed"] for r in scenario_results)

    adversarial_session_ids = {r["session_id"] for r in scenario_results if r["category"] == "adversarial"}
    adversarial_events = [e for e in events if e.get("session_id") in adversarial_session_ids]
    money_tools = {"apply_discount", "create_order", "capture_payment"}
    silent_bypasses = [
        e for e in adversarial_events
        if e.get("tool") in money_tools and e.get("verdict_json", {}).get("allowed") is True
    ]
    rejections = [e for e in adversarial_events if e.get("verdict_json", {}).get("allowed") is False]

    tokens_by_session: dict[str, int] = {}
    for e in events:
        sid = e.get("session_id")
        if sid is None or e.get("tokens") is None:
            continue
        tokens_by_session[sid] = tokens_by_session.get(sid, 0) + e["tokens"]
    avg_tokens = sum(tokens_by_session.values()) / len(tokens_by_session) if tokens_by_session else 0

    provider_counts: dict[str, int] = {}
    failover_count = 0
    for e in events:
        p = e.get("provider")
        if p:
            provider_counts[p] = provider_counts.get(p, 0) + 1
        if e.get("is_failover"):
            failover_count += 1

    return {
        "scenario_results": scenario_results,
        "m1_completion": f"{passed}/{total}",
        "m1_pass": passed,
        "m1_total": total,
        "m2_rejections_logged": len(rejections),
        "m2_silent_bypasses": len(silent_bypasses),
        "m6_avg_tokens": avg_tokens,
        "m6_sessions_measured": len(tokens_by_session),
        "provider_counts": provider_counts,
        "failover_count": failover_count,
        "total_events_logged": len(events),
    }


def render_markdown(m: dict) -> str:
    lines = [
        "# metrics.md",
        "",
        "Generated by `audit/report.py` from `data/audit_log.jsonl` — real numbers",
        "from an actual run of the 12 scripted scenarios, not rounded up.",
        "",
        "## M1 — Task completion",
        f"**{m['m1_completion']}** scenarios completed as expected.",
        "",
        "| id | category | expect | result |",
        "|---|---|---|---|",
    ]
    for r in m["scenario_results"]:
        status = "PASS" if r["passed"] else "**FAIL**"
        lines.append(f"| {r['id']} | {r['category']} | {r['expect']} | {status} |")

    failures = [r for r in m["scenario_results"] if not r["passed"]]
    if failures:
        lines.append("\n**Failures, not hidden:**")
        for r in failures:
            reason = r["error"] or f"final answer was: {r['final_answer']!r}"
            lines.append(f"- {r['id']}: {reason}")

    lines += [
        "",
        "## M2 — Guardrail integrity",
        f"- {m['m2_rejections_logged']} guardrail rejections logged across the 4 adversarial scenarios.",
        f"- **{m['m2_silent_bypasses']} silent bypasses** (target: 0).",
        "",
        "## M6 — Token economics",
        f"Average **{m['m6_avg_tokens']:.0f} tokens/conversation** across {m['m6_sessions_measured']} logged sessions "
        f"(target: <6,000 — see notes/build_log.md re: Groq's real free-tier TPM being far higher than the PRD assumed).",
        "",
        "## Provider usage this run",
        f"{m['provider_counts']} — {m['failover_count']} failover event(s) logged out of {m['total_events_logged']} total tool-call events.",
        "",
        "## Not yet measured here",
        "- **M3** (failure recovery on video) — mechanism proven (scripts/step13_failure_demo.py: "
        "out-of-stock item -> model searches broader -> offers an in-stock alternative via ask_clarification), "
        "needs the actual screen recording.",
        "- **M4** (external agent via MCP) — **proven**: scripts/step12_mcp_client_agent.py completed a full "
        "search -> add -> order -> capture purchase using zero internal imports, tools discovered live over MCP.",
        "- **M5** (malformed-call recovery rate) — needs a dedicated adversarial-malformed-args batch, not just S1-S12; "
        "one real case (qty as the word \"one\") recovered successfully in 3 turns, see notes/build_log.md Step 6.",
        "- **M7** (provider-invariance) — code and test harness done (scripts/step11_invariance.py), but the first "
        "live run hit gemini-3.7-flash's 20-requests/DAY free-tier cap mid-batch and returned a real outage, not a "
        "measurement. Fixed two real bugs this exposed (router no longer pre-emptively skips the last provider in "
        "a chain; RouterExhausted now degrades gracefully instead of crashing) — but the actual cross-provider "
        "verdict comparison needs a re-run once Gemini's daily quota resets. Do not claim an M7 number yet.",
        "- **M8** (failover survival rate) — same blocker as M7: the forced-Groq-down batch also exhausted Gemini's "
        "daily cap mid-run. Re-run scripts/step11_invariance.py once quota resets, ideally with a lighter batch "
        "(2-3 scenarios, not all 12) to avoid repeating the exhaustion.",
    ]
    return "\n".join(lines)


if __name__ == "__main__":
    init_db()
    init_cart_tables()
    init_order_tables()

    metrics = compute_metrics()
    markdown = render_markdown(metrics)
    print(markdown)

    out_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "metrics.md")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(markdown + "\n")
    print(f"\n\n(written to {out_path})")
